Web.DreamHome/Controllers/ReportesController.cs
namespace Web.DreamHome.Controllers
{
    using Comun.DreamHome;
    using Negocio.DreamHome.LogicaNegocio;
    using System.Collections.Generic;
    using System.Web.Mvc;


    public class ReportesController : BaseController
    {
        public ActionResult ReporteInmuebles()
        {
            ViewBag.REPORTE = new List<InmueblesRegistradosDTO>();
            return View();
        }


        [HttpPost]
        public ActionResult ReporteInmuebles(InmueblesRegistradosDTO inmueblesRegistradosDTO)
        {
            inmueblesRegistradosDTO.SESSION = GetSession();
            ViewBag.REPORTE = new InmueblesRegistradosRepositorio().ReporteInmueblesRegistrados(inmueblesRegistradosDTO);
            return View();
        }


        public ActionResult ReporteAuditoria()
        {
            ViewBag.REPORTE = new List<InmueblesRegistradosDTO>();
            return View();
        }


        [HttpPost]
        public ActionResult ReporteAuditoria(AuditoriaDTO auditoriaDTO)
        {
            auditoriaDTO.SESSION = GetSession();
            ViewBag.REPORTE = new SistemaRepositorio().ReporteAuditoria(auditoriaDTO);
            return View();
        }

        public ActionResult ReporteOficinas()
        {
            ViewBag.REPORTE = new List<InmueblesRegistradosDTO>();
            return View();
        }


        [HttpPost]
        public ActionResult ReporteOficinas(HistorialLaboralDTO historialLaboralDTO)
        {
            historialLaboralDTO.SESSION = GetSession();
            ViewBag.REPORTE = new OficinasRepositorio().ReporteOficinas(historialLaboralDTO);
            return View();
        }

    }
}

Web.DreamHome/Views/Shared/_Layout.cshtml
@*@using Web.DreamHome.Models*@
@{ 
    var session = Session["Sesion_id"];
    session = session == null ? 0 : session;
}


<script>

    var dato = 0;

    dato = @session;

    if (dato == 0)
    {
        window.location = "@Url.Action("Login","Cuenta")";
    }

</script>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title | DreamHome</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="icon" href="@Url.Content("~/img/favicon.ico")" type="image/x-icon">
    <!-- Inicio Estilos -->
    @Styles.Render("~/Content/PlantillaPrincipalParte1Css")
    @RenderSection("styles", required: false)
    @Styles.Render("~/Content/PlantillaPrincipalParte2Css")
    <!-- Fin Estilos -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <style>
        .pagination > .active > a, .pagination > .active > a:focus, .pagination > .active > a:hover, .pagination > .active > span, .pagination > .active > span:focus, .pagination > .active > span:hover {
            background-color: #3c8dbc;
            border-color: blue;
        }
    </style>
</head>
<body class="hold-transition skin-green sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index", "Home", new { Area = "" })" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>DH</b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>DREAMHOME</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/img/User.png" class="img-circle" height="22" width="22" />
                                <span class="hidden-xs">@Session["Nombre_Usuario"]</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="~/img/User.png" class="img-circle">
                                    <p>
                                        @Session["Nombre_Usuario"]
                                        <small>DreamHome</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <form target="_blank" action="@Url.Action("Perfil", "Cuenta", new { Area = "" })">
                                            <button type="submit" class="btn btn-primary btn-flat">
                                                <span></span> Perfil
                                            </button>
                                        </form>
                                    </div>
                                    <div class="pull-right">
                                        <a class="btn btn-primary btn-flat" href="@Url.Action("LogOff", "Cuenta", new { Area = "" })">Cerrar sesión</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/img/User.png" class="img-circle">
                    </div>
                    <div class="pull-left info">
                        <h6>@Session["Nombre_Usuario"]</h6>
                        <h6>DreamHome</h6>
                    </div>
                </div>
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">Menú</li>
                    <li class="active treeview">
                        <a href="#">
                            <i class="fa fa-dashboard"></i> <span>Inicio</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Index", "Home", new { Area = "" })"><i class="fa fa-circle-o"></i> Principal</a></li>
                        </ul>
                    </li>

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-pie-chart"></i>
                            <span>Administración</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Inicial", "Usuarios")"><i class="fa fa-user-plus"></i> Gestión Usuarios</a></li>
                            
                        </ul>
                    </li>

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-home"></i>
                            <span>Formularios Telematicos</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Inicial", "Oficinas")"><i class="fa fa-home"></i> Oficinas</a></li>
                            <li><a href="@Url.Action("Inicial", "Empleados")"><i class="fa fa-group"></i> Empleados</a></li>
                        </ul>
                    </li>

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-home"></i>
                            <span>Formularios Salpicon</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Inicial", "Inmueble")"><i class="fa fa-home"></i> Inmuebles</a></li>
                            <li><a href="@Url.Action("Inicial", "Clientes")"><i class="fa fa-child"></i> Clientes</a></li>
                        </ul>
                    </li>

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-home"></i>
                            <span>Formularios Maori</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Inicial", "Anuncios")"><i class="fa fa-newspaper-o"></i>Anuncios Periodico</a></li>
                            <li><a href="@Url.Action("Inicial", "ContactosPeriodicos")"><i class="fa fa-search"></i>ContactosPeriodicos</a></li>
                            <li><a href="@Url.Action("Inicial", "Contratos")"><i class="fa fa-search"></i>Contratos Arrendamiento</a></li>
                            <li><a href="@Url.Action("Inicial", "Pagos")"><i class="fa fa-newspaper-o"></i>Pagos</a></li>

                        </ul>
                    </li>

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-home"></i>
                            <span>Formularios Quantum</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Inicial", "Propietarios")"><i class="fa fa-group"></i> Propietarios</a></li>
                            <li><a href="@Url.Action("Inicial", "Visitas")"><i class="fa fa-home"></i> Visitas</a></li>
                        </ul>
                    </li>

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-home"></i>
                            <span>Reportes</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("ReporteOficinas", "Reportes")"><i class="fa fa-area-chart"></i> Reporte Oficinas</a></li>
                            <li><a href="@Url.Action("ReporteInmuebles", "Reportes")"><i class="fa fa-line-chart"></i> Reporte Inmuebles</a></li>
                            <li><a href="@Url.Action("ReporteAuditoria", "Reportes")"><i class="fa fa-bar-chart"></i> Reporte Auditoria</a></li>
                        </ul>
                    </li>

                </ul>

            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 1
            </div>
            <p><strong>&copy; @DateTime.Now.Year <a href="">UT</a></strong>&nbsp;"Universidad del Tolima"</p>
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- Inicio Script -->
    @Scripts.Render("~/bundles/PlantillaPrincipalJs")
    <!-- Fin Script -->
    @RenderSection("scripts", required: false)

    <!-- Script para activar en cualquier parte del formulario la modal de carga -->
    <script src="~/Scripts/Cargando.js"></script>
    <script type="text/javascript">
        function Cargando() {
            waitingDialog.show("Cargando...");
        };

        //Ruta para redireccionar y cerrar sesión
        var redireccionarLogin = "@Url.Action("Login", "Cuenta", new { area = ""})" + "?returnUrl=";
    </script>

    <script src="~/Scripts/CierreProgramadoSesion.js"></script>

</body>
</html>

Web.DreamHome/Views/Shared/_LoginBase.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sistema DreamHome</title>
    <link rel="icon" href="@Url.Content("~/img/favicon.ico")" type="image/x-icon">

    <!-- Global stylesheets -->
    @Styles.Render("~/bundle/LoginCss")
    <!-- /global stylesheets -->
    <!-- Core JS files -->
</head>

<body class="login-container" onload="NoRegresarBoton();">
    <!-- Imagen de fondo -->
    <img class="login-cover" src="@Url.Content("~/img/portada.jpg")" />

    <!-- Contenedor Página -->
    <div class="page-container" >

        <!-- Contenido Página -->
        <div class="page-content" >
            <!-- /Contenido principal -->
            <div class="content-wrapper">
                <!-- Área de contenido -->
                <div class="content pb-20" id="particles-js">
                    @RenderBody()
                </div>
                <!-- /área de contenido-->
            </div>
            <!-- /contenido principal -->
        </div>
        <!-- /contenido Página -->
    </div>
    <!-- /contenedor Página -->

    @*@Scripts.Render("~/bundle/LoginJs")*@
    <!-- /theme JS files -->
    @RenderSection("scripts", required: false)

    <!-- Script para deshabilitar el botón de regresar del explorador -->
    <script type="text/javascript">
        function NoRegresarBoton() {
            window.location.hash = "no-back-button";
            window.location.hash = "Again-No-back-button"; //Chrome
            window.onhashchange = function () { window.location.hash = "Bienvenido_a_la_Universidad_del_Tolima"; }
        }
    </script>
</body>
</html>