Web.DreamHome/Controllers/DetallesInmuebleController.cs
namespace Web.DreamHome.Controllers
{
    using Comun.DreamHome;
    using Negocio.DreamHome.LogicaNegocio;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    public class DetallesInmuebleController : BaseController
    {
        public ActionResult Crear(int _idInmueble)
        {
            ViewBag.IDF_CARACTERISTICA = new SelectList(new ListasRepositorio().ConsultarCaracteristicasInmuebles(), "ID_CARACTERISTICA_PROP", "CARACTERISTICA");
            ViewBag.IDF_INMUEBLE = _idInmueble;
            ViewBag.Mensaje = null;
            return View();
        }

        [HttpPost]
        public ActionResult Crear(DetallesInmueblesDTO detallesInmueblesDTO)
        {
            detallesInmueblesDTO.SESSION = GetSession();
            ViewBag.IDF_CARACTERISTICA = new SelectList(new ListasRepositorio().ConsultarCaracteristicasInmuebles(), "ID_CARACTERISTICA_PROP", "CARACTERISTICA", detallesInmueblesDTO.IDF_CARACTERISTICA);
            return RedirectToAction("Inicial", "Inmueble", new { _mensaje = new DetallesInmueblesRepositorio().ValidarDetallesInmueble(detallesInmueblesDTO) });
        }

        public ActionResult Editar(int _idDetalleInmueble)
        {
            DetallesInmueblesDTO datos = new DetallesInmueblesRepositorio().ConsultaDetallesInmueble(new DetallesInmueblesDTO { ID_DETALLE_INMBL = _idDetalleInmueble, SESSION = GetSession() });
            ViewBag.IDF_CARACTERISTICA = new SelectList(new ListasRepositorio().ConsultarCaracteristicasInmuebles(), "ID_CARACTERISTICA_PROP", "CARACTERISTICA", datos.IDF_CARACTERISTICA);
            return View(datos);
        }

        [HttpPost]
        public ActionResult Editar(DetallesInmueblesDTO detallesInmueblesDTO)
        {
            ViewBag.IDF_CARACTERISTICA = new SelectList(new ListasRepositorio().ConsultarCaracteristicasInmuebles(), "ID_CARACTERISTICA_PROP", "CARACTERISTICA", detallesInmueblesDTO.IDF_CARACTERISTICA);
            detallesInmueblesDTO.SESSION = GetSession();
            return RedirectToAction("Inicial", "Inmueble", new { _mensaje = new DetallesInmueblesRepositorio().ActualizarDetallesInmueble(detallesInmueblesDTO) });
        }

        public ActionResult Eliminar(int _idDetalleInmueble)
        {
            return RedirectToAction("Inicial", "Inmueble", new { _mensaje = new DetallesInmueblesRepositorio().EliminarDetallesInmueble(new DetallesInmueblesDTO { ID_DETALLE_INMBL = _idDetalleInmueble, SESSION = GetSession() }) });
        }

    }
}

Web.DreamHome/Controllers/InmuebleController.cs
namespace Web.DreamHome.Controllers
{
    using Comun.DreamHome;
    using Negocio.DreamHome.LogicaNegocio;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    public class InmuebleController : BaseController
    {
        public ActionResult Inicial(string _mensaje = null)
        {
            ViewBag.Mensaje = _mensaje;

            List<InmueblesDTO> listaInmueblesDTO = new InmueblesRepositorio().ConsultaInmuebles((int)GetSession());

            List<InmueblesRegistradosDTO> listaInmueblesRegistradosDTO = new InmueblesRegistradosRepositorio().ConsultaInmueblesRegistrados(new InmueblesRegistradosDTO { SESSION = GetSession() });

            foreach (var item in listaInmueblesDTO)
            {
                item.DetallesInmueblesDTOs = new DetallesInmueblesRepositorio().ConsultaDetallesInmuebles(new DetallesInmueblesDTO { IDF_INMUEBLE = item.ID_INMUEBLE, SESSION = GetSession()});
                item.InmueblesRegistradosDTOs = listaInmueblesRegistradosDTO.Where(x => x.IDF_INMUEBLE_REG == item.ID_INMUEBLE).ToList();
            }

            return View(listaInmueblesDTO);
        }

        public ActionResult Crear()
        {
            ViewBag.IDF_TIPO_INM = new SelectList(new ListasRepositorio().ConsultarTiposPropiedades(), "ID_TIPO", "NOMBRE_TIPO");
            ViewBag.Mensaje = null;
            return View();
        }

        [HttpPost]
        public ActionResult Crear(InmueblesDTO inmueblesDTO)
        {
            inmueblesDTO.SESSION = GetSession();
            ViewBag.IDF_TIPO_INM = new SelectList(new ListasRepositorio().ConsultarTiposPropiedades(), "ID_TIPO", "NOMBRE_TIPO", inmueblesDTO.IDF_TIPO_INM);
            return RedirectToAction("Inicial", "Inmueble", new { _mensaje = new InmueblesRepositorio().ValidarInmueble(inmueblesDTO) });
        }

        public ActionResult Editar(int _id)
        {
            InmueblesDTO datos = new InmueblesRepositorio().ConsultaInmuebles((int)GetSession()).Where(x => x.ID_INMUEBLE == _id).FirstOrDefault();
            ViewBag.IDF_TIPO_INM = new SelectList(new ListasRepositorio().ConsultarTiposPropiedades(), "ID_TIPO", "NOMBRE_TIPO", datos.IDF_TIPO_INM);
            return View(datos);
        }

        [HttpPost]
        public ActionResult Editar(InmueblesDTO inmueblesDTO)
        {
            ViewBag.IDF_TIPO_INM = new SelectList(new ListasRepositorio().ConsultarTiposPropiedades(), "ID_TIPO", "NOMBRE_TIPO", inmueblesDTO.IDF_TIPO_INM);
            inmueblesDTO.SESSION = GetSession();
            return RedirectToAction("Inicial", "Inmueble", new { _mensaje = new InmueblesRepositorio().ActualizarInmueble(inmueblesDTO) });
        }

        public ActionResult Eliminar(int _id)
        {
            return RedirectToAction("Inicial", "Inmueble", new { _mensaje = new InmueblesRepositorio().EliminarInmueble(new InmueblesDTO { ID_INMUEBLE = _id, SESSION = GetSession() }) });
        }

    }
}

Web.DreamHome/Controllers/InmueblesRegistradosController.cs
namespace Web.DreamHome.Controllers
{
    using Comun.DreamHome;
    using Negocio.DreamHome.LogicaNegocio;
    using System.Linq;
    using System.Web.Mvc;

    public class InmueblesRegistradosController : BaseController
    {
        public ActionResult Crear(int _idInmueble)
        {
            ViewBag.IDF_INMUEBLE_REG = _idInmueble;
            ViewBag.IDF_OFICINA_REG = new SelectList(new ListasRepositorio().ConsultarOficinas(), "ID_OFICINA", "OFICINA");
            ViewBag.IDF_EMPLEADO_REG = new SelectList(new ListasRepositorio().ConsultarEmpleados(), "ID_EMPLEADO", "NOMBRE_RH");
            ViewBag.IDF_ESTADO_REG = new SelectList(new ListasRepositorio().ConsultarEstadosInmuebles(), "ID_ESTADO_INMUEBLE", "ESTADO_INMUEBLE");
            ViewBag.Mensaje = null;
            return View();
        }

        [HttpPost]
        public ActionResult Crear(InmueblesRegistradosDTO inmueblesRegistradosDTO)
        {
            inmueblesRegistradosDTO.SESSION = GetSession();
            ViewBag.IDF_OFICINA_REG = new SelectList(new ListasRepositorio().ConsultarOficinas(), "ID_OFICINA", "OFICINA", inmueblesRegistradosDTO.IDF_OFICINA_REG);
            ViewBag.IDF_EMPLEADO_REG = new SelectList(new ListasRepositorio().ConsultarEmpleados(), "ID_EMPLEADO", "NOMBRE_RH", inmueblesRegistradosDTO.IDF_EMPLEADO_REG);
            ViewBag.IDF_ESTADO_REG = new SelectList(new ListasRepositorio().ConsultarEstadosInmuebles(), "ID_ESTADO_INMUEBLE", "ESTADO_INMUEBLE", inmueblesRegistradosDTO.IDF_ESTADO_REG);
            return RedirectToAction("Inicial", "Inmueble", new { _mensaje = new InmueblesRegistradosRepositorio().ValidarInmueblesRegistrado(inmueblesRegistradosDTO) });
        }

        public ActionResult Editar(int _id)
        {
            InmueblesRegistradosDTO inmueblesRegistradosDTO = new InmueblesRegistradosDTO { SESSION = (int)GetSession() };
            InmueblesRegistradosDTO datos = new InmueblesRegistradosRepositorio().ConsultaInmueblesRegistrados(inmueblesRegistradosDTO).Where(x => x.ID_INMUEBLE_REGISTRADO == _id).FirstOrDefault();
            ViewBag.IDF_OFICINA_REG = new SelectList(new ListasRepositorio().ConsultarOficinas(), "ID_OFICINA", "OFICINA", datos.IDF_OFICINA_REG);
            ViewBag.IDF_EMPLEADO_REG = new SelectList(new ListasRepositorio().ConsultarEmpleados(), "ID_EMPLEADO", "NOMBRE_RH", datos.IDF_EMPLEADO_REG);
            ViewBag.IDF_ESTADO_REG = new SelectList(new ListasRepositorio().ConsultarEstadosInmuebles(), "ID_ESTADO_INMUEBLE", "ESTADO_INMUEBLE", datos.IDF_ESTADO_REG);
            return View(datos);
        }

        [HttpPost]
        public ActionResult Editar(InmueblesRegistradosDTO inmueblesRegistradosDTO)
        {
            ViewBag.IDF_OFICINA_REG = new SelectList(new ListasRepositorio().ConsultarOficinas(), "ID_OFICINA", "OFICINA", inmueblesRegistradosDTO.IDF_OFICINA_REG);
            ViewBag.IDF_EMPLEADO_REG = new SelectList(new ListasRepositorio().ConsultarEmpleados(), "ID_EMPLEADO", "NOMBRE_RH", inmueblesRegistradosDTO.IDF_EMPLEADO_REG);
            ViewBag.IDF_ESTADO_REG = new SelectList(new ListasRepositorio().ConsultarEstadosInmuebles(), "ID_ESTADO_INMUEBLE", "ESTADO_INMUEBLE", inmueblesRegistradosDTO.IDF_ESTADO_REG);
            inmueblesRegistradosDTO.SESSION = GetSession();
            return RedirectToAction("Inicial", "Inmueble", new { _mensaje = new InmueblesRegistradosRepositorio().ActualizarInmueblesRegistrado(inmueblesRegistradosDTO) });
        }

        public ActionResult Eliminar(int _id)
        {
            return RedirectToAction("Inicial", "Inmueble", new { _mensaje = new InmueblesRegistradosRepositorio().EliminarInmueblesRegistrado(new InmueblesRegistradosDTO { ID_INMUEBLE_REGISTRADO = _id, SESSION = GetSession() }) });
        }

    }
}

Web.DreamHome/Views/Inmueble/Inicial.cshtml
@model IEnumerable<Comun.DreamHome.InmueblesDTO>

@{
    ViewBag.Title = "Inicio";
}

@section styles{
    @Styles.Render("~/Content/FormularioCss")
    @Styles.Render("~/Content/bootstrapdataTablesCSS")
}

@section scripts{
    @Scripts.Render("~/bundles/FormularioJs")
    @Scripts.Render("~/bundles/jquerydataTablesJS")

    <script>
        poblarTabla("tbDatos");
    </script>
}

<section class="content-header">
    <h1>
        Empresa de Arrendamiento y Compra de Inmuebles DreamHome DH
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Inicio</a></li>
        <li class="active">Listar</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <!-- Etapa Verificación -->
        <div class="col-md-12">
            <!-- /.box -->
            <div class="box box-primary">
                <div class="box-header">
                    <div class="text-right">
                        <div class="col-md-6 text-left">
                            <h3 class="box-title">Lista inmuebles</h3>
                        </div>
                        <div class="col-md-6 text-right">
                            <button type="button" class="btn btn-primary btn-sm" onclick="location.href='@Url.Action("Crear", "Inmueble")';">
                                <span class="glyphicon glyphicon-plus"></span> Nuevo
                            </button>
                        </div>
                    </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                    @if (ViewBag.Mensaje != null)
                    {
                        <div class="alert alert-info alert-dismissible"><h4 class="text-center"> @ViewBag.Mensaje <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button></h4></div>
                        <br />
                    }
                    <table id="tbDatos" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th></th>
                                <th></th>
                                <th>
                                    <p>Id Inmueble</p>
                                </th>
                                <th>
                                    <p>Tipo</p>
                                </th>
                                <th>
                                    <p>Dirección</p>
                                </th>
                                <th>
                                    <p>Apartado</p>
                                </th>
                                <th>
                                    <p>Fecha creación</p>
                                </th>
                                <th>
                                    <p>Activo</p>
                                </th>
                                <th>
                                    <p>Detalle inmueble</p>
                                </th>
                                <th>
                                    <p>Detalle registro</p>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td></td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn btn-primary" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                            <span class="glyphicon glyphicon-align-center"></span>
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                            <li><a href="@Url.Action("Crear", "InmueblesRegistrados", new { _idInmueble = item.ID_INMUEBLE })"><i class="fa fa-pencil-square-o"></i> Registrar</a></li>
                                            <li><a href="@Url.Action("Crear", "DetallesInmueble", new { _idInmueble = item.ID_INMUEBLE })"><i class="fa fa-pencil-square-o"></i> Agregar detalles</a></li>
                                            <li><a href="@Url.Action("Editar", "Inmueble", new { _id = item.ID_INMUEBLE })"><i class="fa fa-refresh"></i> Actualizar</a></li>
                                            <li><a href="@Url.Action("Eliminar", "Inmueble", new { _id = item.ID_INMUEBLE })"><i class="fa fa-trash"></i> Eliminar</a></li>
                                        </ul>
                                    </div>
                                </td>
                                <td>@item.ID_INMUEBLE</td>
                                <td>@item.IDF_TIPO_INM_STR</td>
                                <td>@item.DIRECCION_INM</td>
                                <td>@item.APARTADO_INM</td>
                                <td>@item.FECHA_INM</td>
                                <td>@item.ACTIVO_INM</td>
                                <td>
                                    <ul>
                                        @foreach (var item2 in item.DetallesInmueblesDTOs)
                                        {
                                            <li>@item2.CARACTERISTICA - @item2.VALOR  &nbsp &nbsp<a style="cursor:pointer;color:blue" title="Actualizar Detalle" class="fa fa-refresh" href="@Url.Action("Editar","DetallesInmueble", new { _idDetalleInmueble = item2.ID_DETALLE_INMBL })"></a><b>&nbsp -  &nbsp</b><a style="cursor:pointer;color:darkred" title="Eliminar Detalle" class="fa fa-close" href="@Url.Action("Eliminar","DetallesInmueble", new { _idDetalleInmueble = item2.ID_DETALLE_INMBL })"></a></li>
                                        }
                                    </ul>
                                </td>
                                <td>
                                    <ul>
                                        @foreach (var item2 in item.InmueblesRegistradosDTOs)
                                        {
                                            <li>@item2.OFICINA - @item2.NOMBRE_RH - @item2.ESTADO_INMUEBLE  &nbsp &nbsp<a style="cursor:pointer;color:blue" title="Actualizar Detalle" class="fa fa-refresh" href="@Url.Action("Editar","InmueblesRegistrados", new { _id = item2.ID_INMUEBLE_REGISTRADO })"></a><b>&nbsp -  &nbsp</b><a style="cursor:pointer;color:darkred" title="Eliminar Detalle" class="fa fa-close" href="@Url.Action("Eliminar","InmueblesRegistrados", new { _id = item2.ID_INMUEBLE_REGISTRADO })"></a></li>
                                        }
                                    </ul>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>

</section>