Web.DreamHome/Controllers/ContactosEmpleadosController.cs
namespace Web.DreamHome.Controllers
{
    using Comun.DreamHome;
    using Negocio.DreamHome.LogicaNegocio;
    using System.Linq;
    using System.Web.Mvc;

    public class ContactosEmpleadosController : BaseController
    {
        public ActionResult Crear(int _idEmpleado)
        {
            ViewBag.IDF_TIPO_CONTACTO_CNTCT = new SelectList(new ListasRepositorio().ConsultarTiposContactos(), "ID_TIPO_CONTACTO", "TIPO_CONTACTO");
            ViewBag.IDF_EMPLEADO_CNTCT = _idEmpleado;
            ViewBag.Mensaje = null;
            return View();
        }

        [HttpPost]
        public ActionResult Crear(ContactosEmpleadosDTO contactosEmpleadosDTO)
        {
            contactosEmpleadosDTO.SESSION = GetSession();
            ViewBag.IDF_TIPO_CONTACTO_CNTCT = new SelectList(new ListasRepositorio().ConsultarTiposContactos(), "ID_TIPO_CONTACTO", "TIPO_CONTACTO", contactosEmpleadosDTO.IDF_TIPO_CONTACTO_CNTCT);
            return RedirectToAction("Inicial", "Empleados", new { _mensaje = new ContactosEmpleadosRepositorio().ValidarContactosEmpleado(contactosEmpleadosDTO) });
        }

        public ActionResult Editar(int _id)
        {
            ContactosEmpleadosDTO datos = new ContactosEmpleadosRepositorio().ConsultaContactosEmpleados((int)GetSession()).Where(x => x.ID_CONTACTO_EMPLEADO == _id).FirstOrDefault();
            ViewBag.IDF_TIPO_CONTACTO_CNTCT = new SelectList(new ListasRepositorio().ConsultarTiposContactos(), "ID_TIPO_CONTACTO", "TIPO_CONTACTO", datos.IDF_TIPO_CONTACTO_CNTCT);
            return View(datos);
        }

        [HttpPost]
        public ActionResult Editar(ContactosEmpleadosDTO contactosEmpleadosDTO)
        {
            ViewBag.IDF_TIPO_CONTACTO_CNTCT = new SelectList(new ListasRepositorio().ConsultarTiposContactos(), "ID_TIPO_CONTACTO", "TIPO_CONTACTO", contactosEmpleadosDTO.IDF_TIPO_CONTACTO_CNTCT);
            contactosEmpleadosDTO.SESSION = GetSession();
            return RedirectToAction("Inicial", "Empleados", new { _mensaje = new ContactosEmpleadosRepositorio().ActualizarContactosEmpleado(contactosEmpleadosDTO) });
        }

        public ActionResult Eliminar(int _id)
        {
            return RedirectToAction("Inicial", "Empleados", new { _mensaje = new ContactosEmpleadosRepositorio().EliminarContactosEmpleado(new ContactosEmpleadosDTO { ID_CONTACTO_EMPLEADO = _id, SESSION = GetSession() }) });
        }

    }
}

Web.DreamHome/Controllers/EmpleadosController.cs
namespace Web.DreamHome.Controllers
{
    using Comun.DreamHome;
    using Negocio.DreamHome.LogicaNegocio;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    public class EmpleadosController : BaseController
    {
        public ActionResult Inicial(string _mensaje = null)
        {
            ViewBag.Mensaje = _mensaje;

            List<EmpleadosDTO> listaEmpleados = new EmpleadosRepositorio().ConsultaEmpleados((int)GetSession());
            List<HistorialLaboralDTO> listaHistorialLaboral = new HistorialLaboralRepositorio().ConsultaHistorialLaboral((int)GetSession());
            List<ContactosEmpleadosDTO> listaContactos = new ContactosEmpleadosRepositorio().ConsultaContactosEmpleados((int)GetSession());

            foreach (var item in listaEmpleados)
            {
                item.HistorialLaboralDTOs = listaHistorialLaboral.Where(x => x.IDF_EMPLEADO_HST == item.ID_EMPLEADO).ToList();
                item.ContactosEmpleadosDTOs = listaContactos.Where(x => x.IDF_EMPLEADO_CNTCT == item.ID_EMPLEADO).ToList();
            }

            return View(listaEmpleados);
        }

        public ActionResult Crear()
        {
            ViewBag.IDF_GENERO_RH = new SelectList(new ListasRepositorio().ConsultarGeneros(), "ID_GENERO", "GENERO");
            ViewBag.IDF_USUARIO_RH = new SelectList(new ListasRepositorio().ConsultarUsuarios(), "Usuario_id", "Nombre_Usuario");
            ViewBag.Mensaje = null;
            return View();
        }

        [HttpPost]
        public ActionResult Crear(EmpleadosDTO empleadosDTO)
        {
            empleadosDTO.SESSION = GetSession();
            ViewBag.IDF_GENERO_RH = new SelectList(new ListasRepositorio().ConsultarGeneros(), "ID_GENERO", "GENERO", empleadosDTO.IDF_GENERO_RH);
            ViewBag.IDF_USUARIO_RH = new SelectList(new ListasRepositorio().ConsultarUsuarios(), "Usuario_id", "Nombre_Usuario", empleadosDTO.IDF_USUARIO_RH);
            return RedirectToAction("Inicial", "Empleados", new { _mensaje = new EmpleadosRepositorio().ValidarEmpleado(empleadosDTO) });
        }

        public ActionResult Editar(int _id)
        {
            EmpleadosDTO datos = new EmpleadosRepositorio().ConsultaEmpleados((int)GetSession()).Where(x => x.ID_EMPLEADO == _id).FirstOrDefault();
            ViewBag.IDF_GENERO_RH = new SelectList(new ListasRepositorio().ConsultarGeneros(), "ID_GENERO", "GENERO", datos.IDF_GENERO_RH);
            ViewBag.IDF_USUARIO_RH = new SelectList(new ListasRepositorio().ConsultarUsuarios(), "Usuario_id", "Nombre_Usuario", datos.IDF_USUARIO_RH);
            return View(datos);
        }

        [HttpPost]
        public ActionResult Editar(EmpleadosDTO empleadosDTO)
        {
            ViewBag.IDF_GENERO_RH = new SelectList(new ListasRepositorio().ConsultarGeneros(), "ID_GENERO", "GENERO", empleadosDTO.IDF_GENERO_RH);
            ViewBag.IDF_USUARIO_RH = new SelectList(new ListasRepositorio().ConsultarUsuarios(), "Usuario_id", "Nombre_Usuario", empleadosDTO.IDF_USUARIO_RH);
            empleadosDTO.SESSION = GetSession();
            return RedirectToAction("Inicial", "Empleados", new { _mensaje = new EmpleadosRepositorio().ActualizarEmpleado(empleadosDTO) });
        }

        public ActionResult Eliminar(int _id)
        {
            return RedirectToAction("Inicial", "Empleados", new { _mensaje = new EmpleadosRepositorio().EliminarEmpleado(new EmpleadosDTO { ID_EMPLEADO = _id, SESSION = GetSession() }) });
        }

    }
}

Web.DreamHome/Controllers/HistorialLaboralController.cs
namespace Web.DreamHome.Controllers
{
    using Comun.DreamHome;
    using Negocio.DreamHome.LogicaNegocio;
    using System.Linq;
    using System.Web.Mvc;

    public class HistorialLaboralController : BaseController
    {
        public ActionResult Crear(int _idEmpleado)
        {
            ViewBag.IDF_EMPLEADO_HST = _idEmpleado;
            ViewBag.IDF_OFCINA_HST = new SelectList(new ListasRepositorio().ConsultarOficinas(), "ID_OFICINA", "OFICINA");
            ViewBag.IDF_CARGO_HST = new SelectList(new ListasRepositorio().ConsultarCargos(), "ID_CARGO", "CARGO");
            ViewBag.Mensaje = null;
            return View();
        }

        [HttpPost]
        public ActionResult Crear(HistorialLaboralDTO historialLaboralDTO)
        {
            historialLaboralDTO.SESSION = GetSession();
            ViewBag.IDF_OFCINA_HST = new SelectList(new ListasRepositorio().ConsultarOficinas(), "ID_OFICINA", "OFICINA", historialLaboralDTO.IDF_OFCINA_HST);
            ViewBag.IDF_CARGO_HST = new SelectList(new ListasRepositorio().ConsultarCargos(), "ID_CARGO", "CARGO", historialLaboralDTO.IDF_CARGO_HST);
            return RedirectToAction("Inicial", "Empleados", new { _mensaje = new HistorialLaboralRepositorio().ValidarHistorialLaboral(historialLaboralDTO) });
        }

        public ActionResult Editar(int _id)
        {
            HistorialLaboralDTO datos = new HistorialLaboralRepositorio().ConsultaHistorialLaboral((int)GetSession()).Where(x => x.ID_HISTORIAL_LABRL == _id).FirstOrDefault();
            ViewBag.IDF_OFCINA_HST = new SelectList(new ListasRepositorio().ConsultarOficinas(), "ID_OFICINA", "OFICINA", datos.IDF_OFCINA_HST);
            ViewBag.IDF_CARGO_HST = new SelectList(new ListasRepositorio().ConsultarCargos(), "ID_CARGO", "CARGO", datos.IDF_CARGO_HST);
            return View(datos);
        }

        [HttpPost]
        public ActionResult Editar(HistorialLaboralDTO historialLaboralDTO)
        {
            ViewBag.IDF_OFCINA_HST = new SelectList(new ListasRepositorio().ConsultarOficinas(), "ID_OFICINA", "OFICINA", historialLaboralDTO.IDF_OFCINA_HST);
            ViewBag.IDF_CARGO_HST = new SelectList(new ListasRepositorio().ConsultarCargos(), "ID_CARGO", "CARGO", historialLaboralDTO.IDF_CARGO_HST);
            historialLaboralDTO.SESSION = GetSession();
            return RedirectToAction("Inicial", "Empleados", new { _mensaje = new HistorialLaboralRepositorio().ActualizarHistorialLaboral(historialLaboralDTO) });
        }

        public ActionResult Eliminar(int _id)
        {
            return RedirectToAction("Inicial", "Empleados", new { _mensaje = new HistorialLaboralRepositorio().EliminarHistorialLaboral(new HistorialLaboralDTO { ID_HISTORIAL_LABRL = _id, SESSION = GetSession() }) });
        }

    }
}

Web.DreamHome/Views/Empleados/Crear.cshtml
@model Comun.DreamHome.EmpleadosDTO

@{
    ViewBag.Title = "Crear";
}

@section styles{
    @Styles.Render("~/Content/FormularioCss")
}

@section scripts{
    @Scripts.Render("~/bundles/FormularioJs")
}

<section class="content-header">
    <h1>
        Crear empleado
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Inicio</a></li>
        <li class="active">Listar</li>
    </ol>
</section>

<section class="content">

    <div class="row">
        <div class="col-md-12" id="notificacion"></div>
    </div>

    @using (Html.BeginForm())
    {
        <!-- Datos básicos-->
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <!-- /.box-header -->
                    <div class="box-header with-border">
                        <div class="text-right">
                            <div class="col-md-6 text-left">
                                <h3 class="box-title"><i class="fa fa-file-text-o"></i> Datos básicos Empleados</h3>
                            </div>
                        </div>
                    </div>

                    <!-- /.box-body -->
                    <div class="box-body">
                        <div class="form-group-sm">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.Label("Usuario Empresarial", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.DropDownList("IDF_USUARIO_RH", null, String.Format("Seleccione el usuario"), htmlAttributes: new { @class = "form-control select2", style = "width: 100%;" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.Label("Género", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.DropDownList("IDF_GENERO_RH", null, String.Format("Seleccione el género"), htmlAttributes: new { @class = "form-control select2", style = "width: 100%;" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.Label("Nombre y apellidos", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.NOMBRE_RH, new { htmlAttributes = new { @class = "form-control", type = "text", @placeholder = "Digite nombres y apellidos del empleado" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="form-group">
                                        @Html.Label("Dirección", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.DIRECCION_RH, new { htmlAttributes = new { @class = "form-control", type = "text", @placeholder = "Digite una dirección" } })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.Label("Apartado", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.APARTADO_RH, new { htmlAttributes = new { @class = "form-control", type = "text", @placeholder = "Digite un apartado" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-footer">
                        <div class="col-md-6 text-left">
                            <a class="btn btn-primary btn-sm" href="@Url.Action("Inicial", "Empleados")">
                                <span class="fa fa-reply"></span> Regresar
                            </a>
                        </div>
                        <div class="col-md-6 text-right">
                            <button type="submit" class="btn btn-primary btn-sm">
                                <span class="fa fa-floppy-o"></span> Guardar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</section>

Web.DreamHome/Views/Empleados/Editar.cshtml
@model Comun.DreamHome.EmpleadosDTO

@{
    ViewBag.Title = "Editar";
}

@section styles{
    @Styles.Render("~/Content/FormularioCss")
}

@section scripts{
    @Scripts.Render("~/bundles/FormularioJs")

    <script>
        AplicarDateTimePlugin();
    </script>
}

<section class="content-header">
    <h1>
        Editar empleado
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Inicio</a></li>
        <li class="active">Listar</li>
    </ol>
</section>

<section class="content">

    <div class="row">
        <div class="col-md-12" id="notificacion"></div>
    </div>

    @using (Html.BeginForm())
    {
        <!-- Datos básicos Empleados-->
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <!-- /.box-header -->
                    <div class="box-header with-border">
                        <div class="text-right">
                            <div class="col-md-6 text-left">
                                <h3 class="box-title"><i class="fa fa-file-text-o"></i> Datos básicos Empleado</h3>
                            </div>
                        </div>
                    </div>

                    <!-- /.box-body -->
                    <div class="box-body">
                        <div class="form-group-sm">
                            <div class="row">
                                <input type="hidden" name="ID_EMPLEADO" id="ID_EMPLEADO" value="@Model.ID_EMPLEADO" />
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.Label("Usuario Empresarial", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.DropDownList("IDF_USUARIO_RH", null, String.Format("Seleccione el usuario"), htmlAttributes: new { @class = "form-control select2", style = "width: 100%;" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.Label("Género", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.DropDownList("IDF_GENERO_RH", null, String.Format("Seleccione el género"), htmlAttributes: new { @class = "form-control select2", style = "width: 100%;" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.Label("Nombre y apellidos", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.NOMBRE_RH, new { htmlAttributes = new { @class = "form-control", type = "text", @placeholder = "Digite nombres y apellidos del empleado" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="form-group">
                                        @Html.Label("Dirección", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.DIRECCION_RH, new { htmlAttributes = new { @class = "form-control", type = "text", @placeholder = "Digite una dirección" } })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.Label("Apartado", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.APARTADO_RH, new { htmlAttributes = new { @class = "form-control", type = "text", @placeholder = "Digite un apartado" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-footer">
                        <div class="col-md-6 text-left">
                            <a class="btn btn-primary btn-sm" href="@Url.Action("Inicial", "Empleados")">
                                <span class="fa fa-reply"></span> Regresar
                            </a>
                        </div>
                        <div class="col-md-6 text-right">
                            <button type="submit" class="btn btn-primary btn-sm">
                                <span class="fa fa-floppy-o"></span> Guardar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</section>

Web.DreamHome/Views/Empleados/Inicial.cshtml
@model IEnumerable<Comun.DreamHome.EmpleadosDTO>

@{
    ViewBag.Title = "Inicio";
}

@section styles{
    @Styles.Render("~/Content/FormularioCss")
    @Styles.Render("~/Content/bootstrapdataTablesCSS")
}

@section scripts{
    @Scripts.Render("~/bundles/FormularioJs")
    @Scripts.Render("~/bundles/jquerydataTablesJS")

    <script>
        poblarTabla("tbDatos");
    </script>
}

<section class="content-header">
    <h1>
        Empleados DreamHome
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Inicio</a></li>
        <li class="active">Listar</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- /.box -->
            <div class="box box-primary">
                <div class="box-header">
                    <div class="text-right">
                        <div class="col-md-6 text-left">
                            <h3 class="box-title">Lista empleados</h3>
                        </div>
                        <div class="col-md-6 text-right">
                            <button type="button" class="btn btn-primary btn-sm" onclick="location.href='@Url.Action("Crear", "Empleados")';">
                                <span class="glyphicon glyphicon-plus"></span> Nuevo
                            </button>
                        </div>
                    </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                    @if (ViewBag.Mensaje != null)
                    {
                        <div class="alert alert-info alert-dismissible"><h4 class="text-center"> @ViewBag.Mensaje <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button></h4></div>
                        <br />
                    }
                    <table id="tbDatos" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th></th>
                                <th></th>
                                <th>
                                    <p>Id Empleados</p>
                                </th>
                                <th>
                                    <p>Usuario Empresarial</p>
                                </th>
                                <th>
                                    <p>Género</p>
                                </th>
                                <th>
                                    <p>Nombres empleado</p>
                                </th>
                                <th>
                                    <p>Dirección</p>
                                </th>
                                <th>
                                    <p>Apartado</p>
                                </th>
                                <th>
                                    <p>Fecha creación</p>
                                </th>
                                <th>
                                    <p>Historial Laboral</p>
                                </th>
                                <th>
                                    <p>Datos de contacto</p>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td></td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn btn-primary" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                            <span class="glyphicon glyphicon-align-center"></span>
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                            <li><a href="@Url.Action("Crear", "HistorialLaboral", new { _idEmpleado = item.ID_EMPLEADO })"><i class="fa fa-pencil-square-o"></i> Agregar historia laboral</a></li>
                                            <li><a href="@Url.Action("Crear", "ContactosEmpleados", new { _idEmpleado = item.ID_EMPLEADO })"><i class="fa fa-pencil-square-o"></i> Agregar datos de contacto</a></li>
                                            <li><a href="@Url.Action("Editar", "Empleados", new { _id = item.ID_EMPLEADO })"><i class="fa fa-refresh"></i> Actualizar</a></li>
                                            <li><a href="@Url.Action("Eliminar", "Empleados", new { _id = item.ID_EMPLEADO })"><i class="fa fa-trash"></i> Eliminar</a></li>
                                        </ul>
                                    </div>
                                </td>
                                <td>@item.ID_EMPLEADO</td>
                                <td>@item.USUARIO</td>
                                <td>@item.GENERO</td>
                                <td>@item.NOMBRE_RH</td>
                                <td>@item.DIRECCION_RH</td>
                                <td>@item.APARTADO_RH</td>
                                <td>@item.FECHA_RH</td>
                                <td>
                                    <ul>
                                        @foreach (var item2 in item.HistorialLaboralDTOs)
                                        {
                                            <li>@item2.CARGO - @item2.OFICINA  &nbsp &nbsp<a style="cursor:pointer;color:blue" title="Actualizar" class="fa fa-refresh" href="@Url.Action("Editar","HistorialLaboral", new { _id = item2.ID_HISTORIAL_LABRL })"></a><b>&nbsp -  &nbsp</b><a style="cursor:pointer;color:darkred" title="Eliminar" class="fa fa-close" href="@Url.Action("Eliminar","HistorialLaboral", new { _id = item2.ID_HISTORIAL_LABRL })"></a></li>
                                        }
                                    </ul>
                                </td>
                                <td>
                                    <ul>
                                        @foreach (var item2 in item.ContactosEmpleadosDTOs)
                                        {
                                            <li>@item2.TIPO_CONTACTO: @item2.DATO_CNTCT_EMP  &nbsp &nbsp<a style="cursor:pointer;color:blue" title="Actualizar" class="fa fa-refresh" href="@Url.Action("Editar","ContactosEmpleados", new { _id = item2.ID_CONTACTO_EMPLEADO })"></a><b>&nbsp -  &nbsp</b><a style="cursor:pointer;color:darkred" title="Eliminar" class="fa fa-close" href="@Url.Action("Eliminar","ContactosEmpleados", new { _id = item2.ID_CONTACTO_EMPLEADO })"></a></li>
                                        }
                                    </ul>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>

</section>