Web.DreamHome/Controllers/ContactosPropietariosController.cs
namespace Web.DreamHome.Controllers
{
    using Comun.DreamHome;
    using Negocio.DreamHome.LogicaNegocio;
    using System.Linq;
    using System.Web.Mvc;

    public class ContactosPropietariosController : BaseController
    {
        public ActionResult Crear(int _idPropietario)
        {
            ViewBag.IDF_TIPO_CONTACTO_PROP = new SelectList(new ListasRepositorio().ConsultarTiposContactos(), "ID_TIPO_CONTACTO", "TIPO_CONTACTO");
            ViewBag.IDF_PROPIETARIO_CNTCT = _idPropietario;
            ViewBag.Mensaje = null;
            return View();
        }

        [HttpPost]
        public ActionResult Crear(ContactosPropietariosDTO contactosPropietariosDTO)
        { 
            contactosPropietariosDTO.SESSION = GetSession();
            ViewBag.IDF_TIPO_CONTACTO_PROP = new SelectList(new ListasRepositorio().ConsultarTiposContactos(), "ID_TIPO_CONTACTO", "TIPO_CONTACTO", contactosPropietariosDTO.IDF_TIPO_CONTACTO_PROP);
            return RedirectToAction("Inicial", "Propietarios", new { _mensaje = new ContactosPropietariosRepositorio().ValidarContactosPropietario(contactosPropietariosDTO) });
        }

        public ActionResult Editar(int _id)
        {
            ContactosPropietariosDTO datos = new ContactosPropietariosRepositorio().ConsultaContactosPropietarios((int)GetSession()).Where(x => x.ID_CONTACTO_PROPIETARIO == _id).FirstOrDefault();
            ViewBag.IDF_TIPO_CONTACTO_PROP = new SelectList(new ListasRepositorio().ConsultarTiposContactos(), "ID_TIPO_CONTACTO", "TIPO_CONTACTO", datos.IDF_TIPO_CONTACTO_PROP);
            return View(datos);
        }

        [HttpPost]
        public ActionResult Editar(ContactosPropietariosDTO contactosPropietariosDTO)
        {
            ViewBag.IDF_TIPO_CONTACTO_PROP = new SelectList(new ListasRepositorio().ConsultarTiposContactos(), "ID_TIPO_CONTACTO", "TIPO_CONTACTO", contactosPropietariosDTO.IDF_TIPO_CONTACTO_PROP);
            contactosPropietariosDTO.SESSION = GetSession();
            return RedirectToAction("Inicial", "Propietarios", new { _mensaje = new ContactosPropietariosRepositorio().ActualizarContactosPropietario(contactosPropietariosDTO) });
        }

        public ActionResult Eliminar(int _id)
        {
            return RedirectToAction("Inicial", "Propietarios", new { _mensaje = new ContactosPropietariosRepositorio().EliminarContactosPropietario(new ContactosPropietariosDTO { ID_CONTACTO_PROPIETARIO = _id, SESSION = GetSession() }) });
        }

    }
}

Web.DreamHome/Controllers/PropietariosController.cs
namespace Web.DreamHome.Controllers
{
    using Comun.DreamHome;
    using Negocio.DreamHome.LogicaNegocio;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    public class PropietariosController : BaseController
    {
        public ActionResult Inicial(string _mensaje = null)
        {
            ViewBag.Mensaje = _mensaje;

            List<PropietariosDTO> listaPropietarios = new PropietariosRepositorio().ConsultaPropietarios((int)GetSession());

            List<InmueblesPropietariosDTO> listaInmueblesPropietarios = new InmueblesPropietariosRepositorio().ConsultaInmueblesPropietarios((int)GetSession());
            List<ContactosPropietariosDTO> listaContactos = new ContactosPropietariosRepositorio().ConsultaContactosPropietarios((int)GetSession());

            foreach (var item in listaPropietarios)
            {
                item.ContactosPropietariosDTOs = listaContactos.Where(x => x.IDF_PROPIETARIO_CNTCT == item.ID_PROPIETARIO).ToList();
                item.InmueblesPropietariosDTOs = listaInmueblesPropietarios.Where(x => x.IDF_PROPIETARIO_PROP == item.ID_PROPIETARIO).ToList();
            }

            return View(listaPropietarios);
        }

        public ActionResult Crear()
        {
            ViewBag.IDF_USUARIO_PROP = new SelectList(new ListasRepositorio().ConsultarUsuarios(), "Usuario_id", "Nombre_Usuario");
            ViewBag.Mensaje = null;
            return View();
        }

        [HttpPost]
        public ActionResult Crear(PropietariosDTO propietariosDTO)
        {
            propietariosDTO.SESSION = GetSession();
            ViewBag.IDF_USUARIO_PROP = new SelectList(new ListasRepositorio().ConsultarUsuarios(), "Usuario_id", "Nombre_Usuario", propietariosDTO.IDF_USUARIO_PROP);
            return RedirectToAction("Inicial", "Propietarios", new { _mensaje = new PropietariosRepositorio().Validarpropietario(propietariosDTO) });
        }

        public ActionResult Editar(int _id)
        {
            PropietariosDTO datos = new PropietariosRepositorio().ConsultaPropietarios((int)GetSession()).Where(x => x.ID_PROPIETARIO == _id).FirstOrDefault();
            ViewBag.IDF_USUARIO_PROP = new SelectList(new ListasRepositorio().ConsultarUsuarios(), "Usuario_id", "Nombre_Usuario", datos.IDF_USUARIO_PROP);
            return View(datos);
        }

        [HttpPost]
        public ActionResult Editar(PropietariosDTO propietariosDTO)
        {
            ViewBag.IDF_USUARIO_PROP = new SelectList(new ListasRepositorio().ConsultarUsuarios(), "Usuario_id", "Nombre_Usuario", propietariosDTO.IDF_USUARIO_PROP);
            propietariosDTO.SESSION = GetSession();
            return RedirectToAction("Inicial", "Propietarios", new { _mensaje = new PropietariosRepositorio().Actualizarpropietario(propietariosDTO) });
        }

        public ActionResult Eliminar(int _id)
        {
            return RedirectToAction("Inicial", "Propietarios", new { _mensaje = new PropietariosRepositorio().Eliminarpropietario(new PropietariosDTO { ID_PROPIETARIO = _id, SESSION = GetSession() }) });
        }

    }
}

Web.DreamHome/Views/Propietarios/Crear.cshtml
@model Comun.DreamHome.PropietariosDTO

@{
    ViewBag.Title = "Crear";
}

@section styles{
    @Styles.Render("~/Content/FormularioCss")
}

@section scripts{
    @Scripts.Render("~/bundles/FormularioJs")
}

<section class="content-header">
    <h1>
        Crear Propietario
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Inicio</a></li>
        <li class="active">Listar</li>
    </ol>
</section>

<section class="content">

    <div class="row">
        <div class="col-md-12" id="notificacion"></div>
    </div>

    @using (Html.BeginForm())
    {
        <!-- Datos básicos-->
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <!-- /.box-header -->
                    <div class="box-header with-border">
                        <div class="text-right">
                            <div class="col-md-6 text-left">
                                <h3 class="box-title"><i class="fa fa-file-text-o"></i> Datos básicos Propietarios</h3>
                            </div>
                        </div>
                    </div>

                    <!-- /.box-body -->
                    <div class="box-body">
                        <div class="form-group-sm">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.Label("Usuario Empresarial", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.DropDownList("IDF_USUARIO_PROP", null, String.Format("Seleccione el usuario"), htmlAttributes: new { @class = "form-control select2", style = "width: 100%;" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.Label("Nombre y apellidos", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.NOMBRE_PROP, new { htmlAttributes = new { @class = "form-control", type = "text", @placeholder = "Digite nombres y apellidos del Propietario" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.Label("Dirección", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.DIRECCION_PROP, new { htmlAttributes = new { @class = "form-control", type = "text", @placeholder = "Digite una dirección" } })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.Label("Apartado", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.APARTADO_PROP, new { htmlAttributes = new { @class = "form-control", type = "text", @placeholder = "Digite un apartado" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-footer">
                        <div class="col-md-6 text-left">
                            <a class="btn btn-primary btn-sm" href="@Url.Action("Inicial", "Propietarios")">
                                <span class="fa fa-reply"></span> Regresar
                            </a>
                        </div>
                        <div class="col-md-6 text-right">
                            <button type="submit" class="btn btn-primary btn-sm">
                                <span class="fa fa-floppy-o"></span> Guardar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</section>

Web.DreamHome/Views/Propietarios/Editar.cshtml
@model Comun.DreamHome.PropietariosDTO

@{
    ViewBag.Title = "Editar";
}

@section styles{
    @Styles.Render("~/Content/FormularioCss")
}

@section scripts{
    @Scripts.Render("~/bundles/FormularioJs")

    <script>
        AplicarDateTimePlugin();
    </script>
}

<section class="content-header">
    <h1>
        Editar Propietarios
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Inicio</a></li>
        <li class="active">Listar</li>
    </ol>
</section>

<section class="content">

    <div class="row">
        <div class="col-md-12" id="notificacion"></div>
    </div>

    @using (Html.BeginForm())
    {
        <!-- Datos básicos Propietarioss-->
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <!-- /.box-header -->
                    <div class="box-header with-border">
                        <div class="text-right">
                            <div class="col-md-6 text-left">
                                <h3 class="box-title"><i class="fa fa-file-text-o"></i> Datos básicos Propietarios</h3>
                            </div>
                        </div>
                    </div>

                    <!-- /.box-body -->
                    <div class="box-body">
                        <div class="form-group-sm">
                            <div class="row">
                                <input type="hidden" name="ID_PROPIETARIO" id="ID_PROPIETARIO" value="@Model.ID_PROPIETARIO" />
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.Label("Usuario Empresarial", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.DropDownList("IDF_USUARIO_PROP", null, String.Format("Seleccione el usuario"), htmlAttributes: new { @class = "form-control select2", style = "width: 100%;" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.Label("Nombre y apellidos", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.NOMBRE_PROP, new { htmlAttributes = new { @class = "form-control", type = "text", @placeholder = "Digite nombres y apellidos del Propietario" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.Label("Dirección", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.DIRECCION_PROP, new { htmlAttributes = new { @class = "form-control", type = "text", @placeholder = "Digite una dirección" } })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.Label("Apartado", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.APARTADO_PROP, new { htmlAttributes = new { @class = "form-control", type = "text", @placeholder = "Digite un apartado" } })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-footer">
                        <div class="col-md-6 text-left">
                            <a class="btn btn-primary btn-sm" href="@Url.Action("Inicial", "Propietarios")">
                                <span class="fa fa-reply"></span> Regresar
                            </a>
                        </div>
                        <div class="col-md-6 text-right">
                            <button type="submit" class="btn btn-primary btn-sm">
                                <span class="fa fa-floppy-o"></span> Guardar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</section>

Web.DreamHome/Views/Propietarios/Inicial.cshtml
@model IEnumerable<Comun.DreamHome.PropietariosDTO>

@{
    ViewBag.Title = "Inicio";
}

@section styles{
    @Styles.Render("~/Content/FormularioCss")
    @Styles.Render("~/Content/bootstrapdataTablesCSS")
}

@section scripts{
    @Scripts.Render("~/bundles/FormularioJs")
    @Scripts.Render("~/bundles/jquerydataTablesJS")

    <script>
        poblarTabla("tbDatos");
    </script>
}

<section class="content-header">
    <h1>
        Propietarios DreamHome
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Inicio</a></li>
        <li class="active">Listar</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- /.box -->
            <div class="box box-primary">
                <div class="box-header">
                    <div class="text-right">
                        <div class="col-md-6 text-left">
                            <h3 class="box-title">Lista Propietarios</h3>
                        </div>
                        <div class="col-md-6 text-right">
                            <button type="button" class="btn btn-primary btn-sm" onclick="location.href='@Url.Action("Crear", "Propietarios")';">
                                <span class="glyphicon glyphicon-plus"></span> Nuevo
                            </button>
                        </div>
                    </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                    @if (ViewBag.Mensaje != null)
                    {
                        <div class="alert alert-info alert-dismissible"><h4 class="text-center"> @ViewBag.Mensaje <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button></h4></div>
                        <br />
                    }
                    <table id="tbDatos" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th></th>
                                <th></th>
                                <th>
                                    <p>Id Propietario</p>
                                </th>
                                <th>
                                    <p>Usuario Empresarial</p>
                                </th>
                                <th>
                                    <p>Nombres propietario</p>
                                </th>
                                <th>
                                    <p>Dirección</p>
                                </th>
                                <th>
                                    <p>Apartado</p>
                                </th>
                                <th>
                                    <p>Fecha creación</p>
                                </th>
                                <th>
                                    <p>Inmuebles Asociados</p>
                                </th>
                                <th>
                                    <p>Datos de contacto</p>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td></td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn btn-primary" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                            <span class="glyphicon glyphicon-align-center"></span>
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                            <li><a href="@Url.Action("Crear", "InmueblesPropietarios", new { _idPropietario = item.ID_PROPIETARIO })"><i class="fa fa-pencil-square-o"></i> Asociar Inmueble</a></li>
                                            <li><a href="@Url.Action("Crear", "ContactosPropietarios", new { _idPropietario = item.ID_PROPIETARIO })"><i class="fa fa-pencil-square-o"></i> Agregar datos de contacto</a></li>
                                            <li><a href="@Url.Action("Editar", "Propietarios", new { _id = item.ID_PROPIETARIO })"><i class="fa fa-refresh"></i> Actualizar</a></li>
                                            <li><a href="@Url.Action("Eliminar", "Propietarios", new { _id = item.ID_PROPIETARIO })"><i class="fa fa-trash"></i> Eliminar</a></li>
                                        </ul>
                                    </div>
                                </td>
                                <td>@item.ID_PROPIETARIO</td>
                                <td>@item.USUARIO</td>
                                <td>@item.NOMBRE_PROP</td>
                                <td>@item.DIRECCION_PROP</td>
                                <td>@item.APARTADO_PROP</td>
                                <td>@item.FECHA_PROP</td>
                                <td>
                                    <ul>
                                        @foreach (var item2 in item.InmueblesPropietariosDTOs)
                                        {
                                            <li>@item2.INMUEBLE - @item2.FECHA_PROP  &nbsp &nbsp<a style="cursor:pointer;color:blue" title="Actualizar" class="fa fa-refresh" href="@Url.Action("Editar","InmueblesPropietarios", new { _id = item2.ID_INMUEBLE_PROPIETARIO })"></a><b>&nbsp -  &nbsp</b><a style="cursor:pointer;color:darkred" title="Eliminar" class="fa fa-close" href="@Url.Action("Eliminar","InmueblesPropietarios", new { _id = item2.ID_INMUEBLE_PROPIETARIO })"></a></li>
                                        }
                                    </ul>
                                </td>
                                <td>
                                    <ul>
                                        @foreach (var item2 in item.ContactosPropietariosDTOs)
                                        {
                                            <li>@item2.TIPO_CONTACTO: @item2.DATO_CNTCT_PROP  &nbsp &nbsp<a style="cursor:pointer;color:blue" title="Actualizar" class="fa fa-refresh" href="@Url.Action("Editar","ContactosPropietarios", new { _id = item2.ID_CONTACTO_PROPIETARIO })"></a><b>&nbsp -  &nbsp</b><a style="cursor:pointer;color:darkred" title="Eliminar" class="fa fa-close" href="@Url.Action("Eliminar","ContactosPropietarios", new { _id = item2.ID_CONTACTO_PROPIETARIO })"></a></li>
                                        }
                                    </ul>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>

</section>